name: Workflow Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.26.6'
  GCP_REGION: 'asia-southeast2'
  GCP_ZONE: 'asia-southeast2-a'
  AR_REPO: 'besedka'
  MIG_NAME: 'besedka-mig'
  TEST_MIG_NAME: 'besedka-test-mig'

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: semgrep
        env:
           SEMGREP_RULES: p/default

  osv-scanner:
    name: OSV Scanner
    runs-on: ubuntu-latest
    container: ghcr.io/google/osv-scanner
    env:
      GOTOOLCHAIN: auto
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Scan the code
        run: /osv-scanner -r . || if [ $? -eq 128 ]; then true; else exit $?; fi

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
      with:
        go-version: "1.26"
    - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -v -covermode=atomic -coverprofile=coverage.out -race ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4

  build-and-deploy-test:
    name: Build & Deploy to Test Instance (Spot VM)
    needs: [semgrep, osv-scanner, golangci-lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f # v2

      - name: Log in to GCP Artifact Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Extract metadata for Agent Docker
        id: meta-agent
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.AR_REPO }}/agent
          tags: |
            type=raw,value=test
            type=sha,format=short

      - name: Build and push Agent Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-agent.outputs.tags }}
          labels: ${{ steps.meta-agent.outputs.labels }}
          platforms: linux/amd64

      - name: Trigger Rolling Restart on Test Managed Instance Group
        run: |
          gcloud compute instance-groups managed rolling-action restart ${{ env.TEST_MIG_NAME }} \
            --zone=${{ env.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT }}

  build-and-deploy-prod:
    name: Build & Deploy to Prod Instance (Spot VM with PVC)
    needs: [semgrep, osv-scanner, golangci-lint, test]
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f # v2

      - name: Log in to GCP Artifact Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Extract metadata for Agent Docker
        id: meta-agent
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.AR_REPO }}/agent
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Build and push Agent Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-agent.outputs.tags }}
          labels: ${{ steps.meta-agent.outputs.labels }}
          platforms: linux/amd64

      - name: Trigger Rolling Restart on Prod Managed Instance Group
        run: |
          gcloud compute instance-groups managed rolling-action restart ${{ env.MIG_NAME }} \
            --zone=${{ env.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT }}
